### ISSUE TITLE
2 pods may receive same ip

### ISSUE THREAD

**Issue by stonith** [projectcalico/calico-containers#1295]
@lwr20  Unfortunately, I wasn't able to reproduce to get more information but I applied a basic deployment of 2 nginx pods and both of them received the same ip:

```
NAME                        READY     STATUS    RESTARTS   AGE       IP              NODE
my-nginx-3080244901-o1wk7   1/1       Running   0          3m        192.168.186.4   ip-172-20-92-241.us-west-1.compute.internal
my-nginx-3080244901-wffqp   1/1       Running   0          3m        192.168.186.4   ip-172-20-92-241.us-west-1.compute.internal
```

Deployment:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: us-west-1b
```
