### ISSUE TITLE
calicoctl image tag v.0.23.0 contains dirty commit build of tool

### ISSUE THREAD

**Issue by Stealthii** [projectcalico/calico-containers#1339]
Trailing off from #1222, it seems the version of calicoctl image (v0.23.0) comes with version `v1.0.0-beta-16-gb075ecb-dirty`, which no longer provides pool or other subcommands.

For context, the container definition in the example `calico.yaml` for kubeadm is as follows:
```
# Writes basic configuration to datastore.
- name: configure-calico
  image: calico/ctl:v0.23.0
  args:
  - "pool"
  - "add"
  - "192.168.0.0/16"
  - "--ipip"
  - "--nat-outgoing"
  env:
    # The location of the etcd cluster.
    - name: ETCD_ENDPOINTS
      valueFrom:
        configMapKeyRef:
          name: calico-config
          key: etcd_endpoints
```

Output from `docker run --rm docker.io/calico/ctl:v0.23.0 pool`:
```
Unknown command: "pool"
Usage:
  calicoctl [options] <command> [<args>...]

    create    Create a resource by filename or stdin.
    replace   Replace a resource by filename or stdin.
    apply     Apply a resource by filename or stdin.  This creates a resource
              if it does not exist, and replaces a resource if it does exists.
    delete    Delete a resource identified by file, stdin or resource type and
              name.
    get       Get a resource identified by file, stdin or resource type and
              name.
    config    Manage system-wide and low-level node configuration options.
    ipam      IP address management.
    node      Calico node management.
    version   Display the version of calicoctl.

Options:
  -h --help               Show this screen.
  -l --log-level=<level>  Set the log level (one of panic, fatal, error,
                          warn, info, debug) [default: panic]

Description:
  The calicoctl command line tool is used to manage Calico network and security
  policy, to view and manage endpoint configuration, and to manage a Calico
  node instance.

  See 'calicoctl <command> --help' to read about a specific subcommand.
```

Output from `docker run --rm docker.io/calico/ctl:v0.23.0 version`:
```
Version:      v1.0.0-beta-16-gb075ecb-dirty
Build date:   2016-11-15T02:20:28+0000
Git commit:   b075ecb
```
