### ISSUE TITLE
Unable to delete workloadendpoints from file

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-containers#1392]
I'm seeing this:

```
$ calicoctl delete -f wep.yaml
Failed to execute command: error with field labels = 'map[calico/k8s_ns:default pod-template-hash:1046649697 role:nginx-server]'
```

The file looks like: 

```
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    labels:
      calico/k8s_ns: default
      pod-template-hash: "1046649697"
      role: nginx-server
    name: eth0
    node: k8s-node-02
    orchestrator: k8s
    workload: default.nginx-1046649697-8uo12
  spec:
    interfaceName: cali54bea7bc264
    ipNetworks:
    - 192.168.176.27/32
    mac: ee:21:47:e9:02:8d
    profiles:
    - k8s_ns.default
```
