### ISSUE TITLE
calicoctl as a pod: Calico process is not running

### ISSUE THREAD

**Issue by r0bj** [projectcalico/calico-containers#1418]
My setup:
OS: ubuntu 14.04
kubernetes: 1.4.7
docker-engine: 1.12.1-0~trusty
etcd: 3.0.15
calico-containers: v1.0.0-rc4

I've deployed `calicoctl` as a DaemonSet to have it on every node:
```
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: calicoctl
  namespace: kube-system
  labels:
    k8s-app: calicoctl
spec:
  template:
    metadata:
      labels:
        k8s-app: calicoctl
    spec:
      hostNetwork: true
      containers:
        - name: calicoctl
          image: calico/ctl:v1.0.0-rc4
          command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
          env:
          - name: ETCD_ENDPOINTS
            valueFrom:
              configMapKeyRef:
                name: calico-config
                key: etcd_endpoints
```

Following documentation:
```
# kubectl exec -it -n kube-system calicoctl-c9gdz -- /calicoctl get profiles
NAME
k8s_ns.default
k8s_ns.kube-system
```
Works as expected.

But trying to get node status generates error message:
```
# kubectl exec -it -n kube-system calicoctl-c9gdz -- /calicoctl node status
Calico process is not running.
```

Local version of `calicoctl` on the node works ok:
```
# ./calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 10.14.30.116 | node-to-node mesh | up    | 10:02:53 | Established |
| 10.14.30.117 | node-to-node mesh | up    | 10:02:50 | Established |
| 10.14.30.118 | node-to-node mesh | up    | 10:02:52 | Established |
| 10.14.30.124 | node-to-node mesh | up    | 10:02:51 | Established |
| 10.14.30.110 | node-to-node mesh | up    | 10:02:52 | Established |
| 10.14.30.111 | node-to-node mesh | up    | 10:02:51 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.
```

**Comment by gunjan5** [comment]
@r0bj you'd have to share the PID namespace and mount `/var/run/calico` and `/var/run/bird` in order for the `node status` command to work since the command looks at the process list to see if Calico and BGP backends are running and then talks to the bird socket which needs to be mounted if you're running calicoctl at a pod. See the example DaemonSet below:
```yaml
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: calicoctl
  namespace: kube-system
  labels:
    k8s-app: calicoctl
spec:
  template:
    metadata:
      labels:
        k8s-app: calicoctl
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: calicoctl
          image: calico/ctl:v1.0.0
          command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
          volumeMounts:
            - name: var-run-calico
              mountPath: /var/run/calico
            - name: var-run-bird
              mountPath: /var/run/bird
          env:
          - name: ETCD_ENDPOINTS
            valueFrom:
              configMapKeyRef:
                name: calico-config
                key: etcd_endpoints
      volumes:
        - name: var-run-calico
          hostPath:
            path: /var/run/calico
        - name: var-run-bird
          hostPath:
            path: /var/run/bird
```

Having said that, I'd recommend using `calicoctl` binary since many of the node commands won't work from `calico/ctl` container/pod.
